language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: dJYkslJruERT/afuQW7w7bSoKRTAZ5mFytxmMPwcRBnqLV27y8nR1H/G1v4YveJTYsKIHnhld1m7PIfUBINrRrRK2IOjrmbhyXbmkRFC8dzoB8zYYIGamwiENIC4n74+uHTayql5vYT715DVNMLHY10aj0oluEnQGrUR7LafPsmGVGO4hfqkAGQy6vGXrutsEW9bS8sCbWnUWiQJRji+W9pcAJdtV3SSdEjnYUw8LsT5P5u73zGkHdbub01QEWix8L+9YFm0BvXewA5csA0UGqP+1cnYdAFZIWsdkX19u/btNzhXHXpccakKPH0S8H3UKKWyM5wzyGOeNAV482rkD1714KUXqIfyusx9tXq1pM3WkX4H/6sT06zfhYQ3gyI0BFHLV7yynV/ldBzbU36o7/K6IdjS8jbpExJuuSSY7ExGJrv+dG9BM0P5uvDWbdB0D/U5Vh615kkHwo8IKz+HUtqP5ANhYhMTob5c+a1bDsbzMiLcziv17GYuC9hepFZrZJpXK50rEQ4roMOz/TZWRBEYkDI7xkWgPfWoyHODVnQ8rWn8v5hIlZj49uCPqSe/9XMSh9/xxME31RiRqulM0+mIwgPxONS+Xna31pgRMq8FXImzVX++Xn8cNlDzJNzhyTi63zc/YXaHQ5sGKrEz2eCaj1kd1YDjVF9yRYX/ejo=
  on:
    tags: true
    repo: anrputina/rhf
    python: 3.8
